import 'package:my_app/models/attendance_list.dart';

final AttendanceListModel mockAttendanceData = AttendanceListModel(
  records: [
    AttendanceRecord(
      attendanceId: 1,
      employeeId: 1001,
      employeeName: "John Doe",
      department: "Engineering",
      designation: "Software Engineer",
      workshift: "Morning",
      date: "2025-06-28",
      checkIn: "09:00",
      checkOut: "18:00",
      presentOne: "Present",
      presentTwo: "Present",
      workHours: "9",
      overtimeHours: "1",
      isOvertime: true,
    ),
    AttendanceRecord(
      attendanceId: 2,
      employeeId: 1002,
      employeeName: "Jane Smith",
      department: "HR",
      designation: "HR Manager",
      workshift: "Morning",
      date: "2025-06-28",
      checkIn: "09:15",
      checkOut: "18:05",
      presentOne: "Late",
      presentTwo: "Present",
      workHours: "8.5",
      overtimeHours: "0",
      isOvertime: false,
    ),
    AttendanceRecord(
      attendanceId: 3,
      employeeId: 1003,
      employeeName: "Alice Johnson",
      department: "Finance",
      designation: "Accountant",
      workshift: "Morning",
      date: "2025-06-28",
      checkIn: "08:55",
      checkOut: "17:45",
      presentOne: "Present",
      presentTwo: "Present",
      workHours: "8.75",
      overtimeHours: "0.5",
      isOvertime: true,
    ),
    AttendanceRecord(
      attendanceId: 4,
      employeeId: 1004,
      employeeName: "Bob Brown",
      department: "Sales",
      designation: "Sales Executive",
      workshift: "Morning",
      date: "2025-06-28",
      checkIn: "09:05",
      checkOut: "18:15",
      presentOne: "Present",
      presentTwo: "Late",
      workHours: "8.9",
      overtimeHours: "0",
      isOvertime: false,
    ),
    AttendanceRecord(
      attendanceId: 5,
      employeeId: 1005,
      employeeName: "Carol White",
      department: "Engineering",
      designation: "Senior Developer",
      workshift: "Morning",
      date: "2025-06-28",
      checkIn: "08:45",
      checkOut: "18:30",
      presentOne: "Present",
      presentTwo: "Present",
      workHours: "9.5",
      overtimeHours: "1.2",
      isOvertime: true,
    ),
    AttendanceRecord(
      attendanceId: 6,
      employeeId: 1006,
      employeeName: "David Wilson",
      department: "Marketing",
      designation: "Marketing Lead",
      workshift: "Morning",
      date: "2025-06-28",
      checkIn: "09:20",
      checkOut: "18:10",
      presentOne: "Late",
      presentTwo: "Present",
      workHours: "8.2",
      overtimeHours: "0",
      isOvertime: false,
    ),
    AttendanceRecord(
      attendanceId: 7,
      employeeId: 1007,
      employeeName: "Emma Moore",
      department: "Finance",
      designation: "Auditor",
      workshift: "Morning",
      date: "2025-06-28",
      checkIn: "09:10",
      checkOut: "17:50",
      presentOne: "Present",
      presentTwo: "Present",
      workHours: "8.4",
      overtimeHours: "0",
      isOvertime: false,
    ),
    AttendanceRecord(
      attendanceId: 8,
      employeeId: 1008,
      employeeName: "Frank Taylor",
      department: "Engineering",
      designation: "Developer",
      workshift: "Morning",
      date: "2025-06-28",
      checkIn: "08:50",
      checkOut: "18:20",
      presentOne: "Present",
      presentTwo: "Present",
      workHours: "9",
      overtimeHours: "1",
      isOvertime: true,
    ),
    AttendanceRecord(
      attendanceId: 9,
      employeeId: 1009,
      employeeName: "Grace Lee",
      department: "HR",
      designation: "HR Assistant",
      workshift: "Morning",
      date: "2025-06-28",
      checkIn: "09:05",
      checkOut: "17:55",
      presentOne: "Present",
      presentTwo: "Late",
      workHours: "8.3",
      overtimeHours: "0",
      isOvertime: false,
    ),
    AttendanceRecord(
      attendanceId: 10,
      employeeId: 1010,
      employeeName: "Henry Harris",
      department: "Marketing",
      designation: "Content Writer",
      workshift: "Morning",
      date: "2025-06-28",
      checkIn: "09:00",
      checkOut: "18:00",
      presentOne: "Present",
      presentTwo: "Present",
      workHours: "9",
      overtimeHours: "0.8",
      isOvertime: true,
    ),
  ],
);
